name: PocketBans
main: ProjectInfinity\PocketBans\PocketBans
version: '1.0.0-Beta'
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6]
author: ProjectInfinity
permissions:
  pocketbans.admin:
    description: "Gives the player access to all commands"
    default: op