version: 1
language: 'en'
provider: 'flatfile'
cache:
  xuid:
    max: 5000
    minScore: 2
mysql:
  host: 'localhost'
  port: 3306
  username: 'pocketvote'
  password: 'pocketvote'
  database: 'pocketvote'
  prefix: ''